import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import { headers } from "next/headers";
import Web3ModalProvider from "@/context";
import { Providers } from "./Providers";
import EmptySpace from "@/components/emptySpace/EmptySpace";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <EmptySpace spaceTop={50} />
          <div className="flex justify-center">
            <w3m-button balance="hide" />
          </div>
          <Web3ModalProvider initialState={initialState}>
            {children}
          </Web3ModalProvider>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
